# Generated by Django 4.2.7 on 2025-06-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_choice_id_alter_question_object'),
    ]

    operations = [
        # bodyフィールドをtitleに名前変更
        migrations.RenameField(
            model_name='question',
            old_name='body',
            new_name='title',
        ),
        # objectフィールドをbodyに名前変更
        migrations.RenameField(
            model_name='question',
            old_name='object',
            new_name='body',
        ),
    ]
