# Generated by Django 4.2.7 on 2025-06-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_question_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '初級'), (2, '初級'), (3, '中級'), (4, '中級'), (5, '上級')]),
        ),
    ]
